### ISSUE TITLE
When I use the newest versions of both CodeFormatter and LSPServer, the extension gives warning "LSPServer and CodeFormatter are of different versions".

### ISSUE THREAD

**Issue by Yukai-Qian** [WolframResearch/vscode-wolfram#10]
Mathematica: 13.0
Operating System: Windows 11
CodeFormatter: 1.5.2
LSPServer: 1.5.0

Because both versions are the newest, I am confused why it warns about them being of different versions. I am further confused by the fact that, if I try to install CodeFormatter using command `PacletInstall["CodeFormatter"->"1.5.0"]`, Wolfram gives error "No paclet ... is available is available for download from any currently enabled paclet sites." This leads me to believe that I should, indeed, be using the newest versions of every paclet repectively, instead of keeping their version numbers the same.

However, not wanting to risk it, I downloaded CodeFormatter 1.5.0's source code to build it. Then, the extension gives warning "CodeFormatter and LSPServer are built too far apart". 

These warnings contradict each other. I am confused what versions the extension is trying to tell me to use.

**Comment by bostick** [comment]
Hi,

Where are you seeing the "LSPServer and CodeFormatter are of different versions" warning being printed? Could you post a screenshot?

The "CodeFormatter and LSPServer are built too far apart" warning is suppose to warn about development versions that may have been built too far apart and have different requirements or assumptions. Building both CodeFormatter and LSPServer within 10 days of each other will fix that warning.

I will work to make these warnings more helpful. Also, let me know if you have any problems with functionality.

**Comment by Yukai-Qian** [comment]
Hi Brenton,

I am seeing the "LSPServer and CodeFormatter are of different versions" warning when I install the following paclets and then open a Wolfram script in VS Code:

![Screenshot 2022-05-27 093756](https://user-images.githubusercontent.com/100383998/170710703-933210f5-582e-4be2-90fd-07ee34e2a2f1.png)

![Screenshot 2022-05-27 094109](https://user-images.githubusercontent.com/100383998/170711077-9b2e9288-8417-462a-ac51-4d7b866ea903.png)

While I understand the purpose of these warnings, I believe it is not best to have the version checks dependent on version numbers or build dates since, as is shown here, these paclets - despite both being from Wolfram Research - don't necessarily update synchronously.

**Comment by bostick** [comment]
Precisely. I will fix to only check major.minor for comparing versions, and also only do build date check if the versions are identical.

**Comment by Yukai-Qian** [comment]
Thanks for your timely response and action!
