### ISSUE TITLE
Request of implementation of devcontainer

### ISSUE THREAD

**Issue by akielbowicz** [WolframResearch/vscode-wolfram#11]
Hi, it's been a while since I used Wolfram product and looking into the [docker container](https://hub.docker.com/r/wolframresearch/wolframengine) got here. This project looks promising and seems a perfect match to create a [vscode-dev-container](https://github.com/microsoft/vscode-dev-containers) which will make the setup of a development environment to test things out very trivial. 

Not sure if this is the right place to post the request, let me know if there is a better place. 

Thanks,

**Comment by bostick** [comment]
I'm not sure where a request for creating a development container should go.

**Comment by bostick** [comment]
I don't think there is anything else to do here.
