### ISSUE TITLE
Section folding

### ISSUE THREAD

**Issue by hifismith** [WolframResearch/vscode-wolfram#12]
Can sections and subsections be recognized and folded? In the screenshot I've used cmnd+K+0 to fold everything, but the sections and subsections are expanded. 
<img width="499" alt="image" src="https://user-images.githubusercontent.com/6430337/172163359-02320cfb-eb93-462d-b627-21b9f60e1e4c.png">

**Comment by bostick** [comment]
Sure, I will add this in the next few days.

**Comment by bostick** [comment]
I've added foldingRange support in the latest push. You can test this by building from source, Otherwise, I will be making an update in the next few weeks, and your paclet will update automatically.

**Comment by hifismith** [comment]
@bostick , it appears something has changed in the LSPServer. Section folding has a bug now. It's Christmas Eve so please don't work on this until you're back in the office.

This code shows the "Import" section declaration and then a function, which I've folded, followed by the initialization of variable 'sheets'
<img width="359" alt="image" src="https://user-images.githubusercontent.com/6430337/209438313-f5e30d27-b636-458e-b94e-08fb2335ca7c.png">

This "Import" section goes until line 470, but when I fold it, you'll see it only folds that first function. 
<img width="338" alt="image" src="https://user-images.githubusercontent.com/6430337/209438365-ce0e46b1-ffe5-4e07-a19a-41d6a1539d9f.png">

A couple things stand out.

1. Folding functions is a new feature I believe. It seems to be interfering with the section folding.
2. The function folding is a nice feature that would be awesome to add to other large expression constructs like With, Block, Module, etc. For example, the next bit of code is a function encapsulated within a "With" expression. I am unable to fold it because of the encapsulation. It'd be nice to be able to fold the With statement:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/6430337/209438425-e1918295-a05b-48d1-927f-dfdca46213bc.png">
