### ISSUE TITLE
Selection expansion not working?

### ISSUE THREAD

**Issue by SjoerdSmitWolfram** [WolframResearch/vscode-wolfram#16]
Hi,

I just tried giving this a go, but I can't figure out how the selection expansion is supposed to work. As far as I can tell, selection just expands in the same way as in any other text editor (letter -> word -> line -> everything). Another user I spoke to also mentioned this problem. Is there a special shortcut or something for it?

Selection expansion is extremely important to me; I basically won't consider any plugin that doesn't do it correctly, which is one of the main reasons I'm still on the Eclipse plugin even though it has a number of other issues.

Best,
Sjoerd

**Comment by bostick** [comment]
Yes, VSCode has "Expand Selection" and "Shrink Selection" menu items.

Make sure to update to LSPServer paclet version 1.7.1 to pick up a fix for selection expansion.

**Comment by SjoerdSmitWolfram** [comment]
Ah, yes. That helps.
