### ISSUE TITLE
Blank should be a wordseparator as well

### ISSUE THREAD

**Issue by SjoerdSmitWolfram** [WolframResearch/vscode-wolfram#18]
The Readme file suggests setting up the following characters as word separators:

```
"editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",
```

Shouldn't `_` be one as well? It's really annoying when you can't select `myVar` in `myVar_String` easily.

**Comment by bostick** [comment]
Good point. Added
