### ISSUE TITLE
Starting client failed

### ISSUE THREAD

**Issue by rih-evo** [WolframResearch/vscode-wolfram#21]
I'm having problems using this extension.

System is Windows 10 Enterprise. 
Wolfram Engine Installed on default folder
`C:\Program Files\Wolfram Research\Wolfram Engine\13.1`

The kernel works fine by itself.

![image](https://user-images.githubusercontent.com/114668775/195349112-c643b1b5-8232-4a7c-90e5-f2c63f5caf00.png)

Output tab shows:
```
[Error - 13:53:16] Starting client failed
Launching server using command "C:\Program Files\Wolfram Research\Wolfram Engine\13.1\WolframKernel.exe" failed.
```

My `settings.json` files is like this:

```
{
    "telemetry.enableCrashReporter": true,
    "telemetry.enableTelemetry": true,
    "code-runner.enableAppInsights": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.languageServer": "Default",
    "terminal.integrated.detectLocale": "on",
    "cSpell.userWords": [
    ],
    "cSpell.language": "en-GB",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.shellArgs.windows": null,
    "workbench.colorTheme": "BrentonWL",
    "wolfram.semanticTokens": true,
    "wolfram.command": [
        "`kernel`",
        "-noinit",
        "-noprompt",
        "-nopaclet",
        "-noicon",
        "-nostartuppaclets",
        "-run",
        "Needs[\"LSPServer`\"];LSPServer`StartServer[]"
    ],
    "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?_",
    "[wolfram]": {
        "wolfram.kernel": "C:\\Program Files\\Wolfram Research\\Wolfram Engine\\13.1\\WolframKernel.exe",
        "wolfram.command": [
            "`kernel`",
            "-noinit",
            "-noprompt",
            "-nopaclet",
            "-noicon",
            "-nostartuppaclets",
            "-run",
            "Needs[\"LSPServer`\"];LSPServer`StartServer[]"
        ]
    },
    "wolfram.kernel": "C:\\Program Files\\Wolfram Research\\Wolfram Engine\\13.1\\WolframKernel.exe"
}
```
![image](https://user-images.githubusercontent.com/114668775/195348516-333c8239-fa4a-4bd3-82c3-e0ba64df9757.png)

**Comment by bostick** [comment]
I'm not able to reproduce this.

It would be good to first collect some information about your setup.

Can you evaluate:
```
PacletFind /@ {"CodeParser", "CodeInspector", "CodeFormatter", "LSPServer"} 
```

and paste the result?

**Comment by bostick** [comment]
*sigh*

OK, running wolframscript may be giving a different result than the WolframKernel.exe in your command (and the pasted result is huge and unreadable).

Please start the WolframKernel.exe that you specified in the command and evaluate

```
PacletFind /@ {"CodeParser", "CodeInspector", "CodeFormatter", "LSPServer"}
```

and paste the result.

I'm interested in what the kernel that you want to use is doing.


I would also like the versions of VSCode itself and the Wolfram extension that you are using.

You can find the VSCode version by going to Help > About

You can find the Wolfram extension version by going to Extensions button on far left-side, going to your Installed extensions, finding Wolfram Language, clicking on it 


I have some questions and other things to try:

Has this ever worked? Or did it recently stop working?

Do you ever run multiple kernels? There may be stray kernel processes that are still running and you are hitting a license limit.

Do you have different users on the machine? Could there be a permissions problem?

Assuming that are running everything as the user `rodolfo.hermans`, check and see if the directory `C:\Users\rodolfo.hermans\AppData\Local\Temp\Wolfram-LSPServer` exists.

This is something that I suggest for people to run when the kernel is crashing, and I do not think it will be very useful here, but I would just like to get more information.

Start the WolframKernel.exe that you specified in the command and evaluate:

```
Needs["LSPServer`"]
LSPServer`RunServerDiagnostic[{"C:\\Program Files\\Wolfram Research\\Wolfram Engine\\13.1\\WolframKernel.exe", "-noinit", "-noprompt", "-nopaclet", "-noicon", "-nostartuppaclets", "-run", "Needs[\"LSPServer`\"];LSPServer`StartServer[]"}]
```

and paste the result.

Maybe there will be something useful here.

**Comment by rih-evo** [comment]
```
Wolfram Language 13.1.0 Engine for Microsoft Windows (64-bit)
Copyright 1988-2022 Wolfram Research, Inc.

In[1]:= Needs["LSPServer`"]

In[2]:= LSPServer`RunServerDiagnostic[{"C:\\Program Files\\Wolfram Research\\Wolfram Engine\\13.1\\WolframKernel.exe", "-noinit", "-noprompt", "-nopaclet", "-noicon", "-nostartuppaclets", "-run", "Needs[\"LSPServer`\"];LSPServer`StartServer[]"}]
Running Language Server diagnostic...

IMPORTANT: Make sure that all other kernels are shut down before running this diagnostic.
Transient license limit errors may give false negatives.

INFORMATION: Host Kernel: C:\Program Files\Wolfram Research\Wolfram Engine\13.1\WolframKernel.exe
INFORMATION: Host Kernel version: 13.0
INFORMATION: Host Kernel Directory[]: C:\Program Files\Wolfram Research\Wolfram Engine\13.1
INFORMATION: Host Kernel $MaxLicenseProcesses: 2
INFORMATION: Host Kernel LSPServer version: 1.7.1
INFORMATION: Host Kernel CodeParser version: 1.7.1
INFORMATION: Host Kernel CodeInspector version: 1.7
INFORMATION: Host Kernel CodeFormatter version: 1.7
INFORMATION: Host Kernel LSPServer build date: Tue 30 Aug 2022 13:57:46
INFORMATION: Host Kernel CodeParser build date: Tue 30 Aug 2022 14:00:14
INFORMATION: Host Kernel CodeInspector build date: Fri 01 Jul 2022 11:58:38
INFORMATION: Host Kernel CodeFormatter build date: Fri 01 Jul 2022 13:03:52

Start Stage 1
Checking whether bug 410895 is present and work-around is needed...
Starting Mini Server kernel with command: 
 
>   {C:\Program Files\Wolfram Research\Wolfram Engine\13.1\WolframKernel.exe, -noinit, -noprompt, 
 
>    -nopaclet, -noicon, -nostartuppaclets, -run, 
 
>    Test410895[(*"*)];ToExpression[FromCharacterCode[{78, 101, 101, 100, 115, 91, 34, 76, 83, 80, 83,\
 
>     101, 114, 118, 101, 114, 96, 34, 93, 59, 76, 83, 80, 83, 101, 114, 118, 101, 114, 96, 83, 101,\
 
>     114, 118, 101, 114, 68, 105, 97, 103, 110, 111, 115, 116, 105, 99, 115, 96, 83, 116, 97, 114,\
 
>     116, 77, 105, 110, 105, 83, 101, 114, 118, 101, 114, 91, 93}]]}
Waiting maximum of 30 seconds for any hangs.
Sanity checking...
Sanity check was successful.
Testing bug 410895...
double-quotes are kept; bug 410895 is NOT present; NO work-around needed
Testing bug 410895 was successful.
Exiting...
waiting 2 seconds for exit...
Exiting was successful.
INFO: Exit code: 0
Done Stage 1

Start Stage 2
Now running actual diagnostics...
$WorkaroundBug410895: False
Starting Language Server kernel with command: 
 
>   {C:\Program Files\Wolfram Research\Wolfram Engine\13.1\WolframKernel.exe, -noinit, -noprompt, 
 
>    -nopaclet, -noicon, -nostartuppaclets, -run, Needs["LSPServer`"];LSPServer`StartServer[]}
Waiting maximum of 30 seconds for any hangs.
Writing initialize message...
initialize message was successful.
Writing diagnostics message...
INFORMATION: Server Kernel: C:\Program Files\Wolfram Research\Wolfram Engine\13.1\WolframKernel.exe
INFORMATION: Server Kernel $CommandLine //InputForm: 
 
>   {"C:\\Program Files\\Wolfram Research\\Wolfram Engine\\13.1\\WolframKernel.exe", "-noinit", 
 
>    "-noprompt", "-nopaclet", "-noicon", "-nostartuppaclets", "-run", 
 
>    "Needs[\"LSPServer`\"];LSPServer`StartServer[]"}
INFORMATION: Server Kernel Directory[]: C:\Program Files\Wolfram Research\Wolfram Engine\13.1
INFORMATION: Server Kernel $VersionNumber: 13.0
INFORMATION: Server Kernel $MaxLicenseProcesses: 2
INFORMATION: Server Kernel LSPServer version: 1.7.1
INFORMATION: Server Kernel CodeParser version: 1.7.1
INFORMATION: Server Kernel CodeInspector version: 1.7
INFORMATION: Server Kernel CodeFormatter version: 1.7
INFORMATION: Server Kernel LSPServer build date: Tue 30 Aug 2022 13:57:46
INFORMATION: Server Kernel CodeParser build date: Tue 30 Aug 2022 14:00:14
INFORMATION: Server Kernel CodeInspector build date: Fri 01 Jul 2022 11:58:38
INFORMATION: Server Kernel CodeFormatter build date: Fri 01 Jul 2022 13:03:52
diagnostics message was successful.
Writing shutdown message...
shutdown message was successful.
Writing exit message...
waiting 2 seconds for exit...
exit message was successful.
INFO: Time to initialize server: 5.5287 seconds
INFO: Exit code: 0
Done Stage 2

No problems found.

In[3]:= 
```

![image](https://user-images.githubusercontent.com/114668775/195795188-ce1a4927-0135-4b4d-b45e-e2bc13d76159.png)

**Comment by rih-evo** [comment]
VS Code 1.72.1
![image](https://user-images.githubusercontent.com/114668775/195796519-f700b6f8-f72a-41ba-8213-a9655c5bf336.png)

Extension v1.7.0
![image](https://user-images.githubusercontent.com/114668775/195796763-822856ea-755b-45eb-9f73-066151737bc6.png)

_Has this ever worked?_
No, never worked

_Do you ever run multiple kernels? There may be stray kernel processes that are still running and you are hitting a license limit._
I am aware of that problem, but I have tried after restarting without opening other kernels before testing the VS Code extension. 

_Do you have different users on the machine? Could there be a permissions problem?_
I do not have Administrator privileges in this Machine, no other users are concretely logged in.

`C:\Users\rodolfo.hermans\AppData\Local\Temp\Wolfram-LSPServer` folder exists but it's empty

**Comment by bostick** [comment]
Thank you for all of the info, and thank you for trying all of these suggestions.

We will get to the bottom of this.

You do have the latest versions of everything, so nothing to fix there.

The diagnostics did not find anything.

The fact that `Wolfram-LSPServer` directory means that the VSCode side of things is working.


If you are willing, the next I'd like to try is to turn on some debugging in the kernel and see if anything useful is logged.

In your `settings.json`, please modify the `"wolfram.command"` entry (and you can remove the `"[wolfram]"` entry)

Change it to this, and restart VSCode and try again:
```
"wolfram.command": [
        "`kernel`",
        "-noinit",
        "-noprompt",
        "-nopaclet",
        "-nostartuppaclets",
        "-noicon",
        "-run",
        "Needs[\"LSPServer`\"];LSPServer`$Debug2=True;LSPServer`StartServer[\"C:/Users/rodolfo.hermans/AppData/Local/Temp/Wolfram-LSPServer\"]"
    ]
```

With any luck, after you restart and try, there will be a log file with some contents in that directory.

Let me know whether or not there is a log file, and paste its contents here.

**Comment by rih-evo** [comment]
Thanks for all your help. With the example code...

```
Which[a, b, a, b]
```

![image](https://user-images.githubusercontent.com/114668775/195875475-97eeb981-43c9-44ca-ad15-da57d1568975.png)


Now it works... but


![image](https://user-images.githubusercontent.com/114668775/195877416-f3590ffc-6e51-4af8-ba1d-86e9bf7e5d50.png)


Where do I find the log file?

This if how the `settings.json` file looks like now


```
{
    "telemetry.enableCrashReporter": true,
    "telemetry.enableTelemetry": true,
    "code-runner.enableAppInsights": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.languageServer": "Default",
    "terminal.integrated.detectLocale": "on",
    "cSpell.userWords": [
    ],
    "cSpell.language": "en-GB",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.shellArgs.windows": null,
    "workbench.colorTheme": "BrentonWL",
    "wolfram.semanticTokens": true,
    "wolfram.command": [
    
        "`kernel`",
        "-noinit",
        "-noprompt",
        "-nopaclet",
        "-nostartuppaclets",
        "-noicon",
        "-run",
        "Needs[\"LSPServer`\"];LSPServer`$Debug2=True;LSPServer`StartServer[\"C:/Users/rodolfo.hermans/AppData/Local/Temp/Wolfram-LSPServer\"]"
    ],
    "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?_",
    "wolfram.kernel": "C:\\Program Files\\Wolfram Research\\Wolfram Engine\\13.1\\WolframKernel.exe",
    "wolframLanguageNotebook.kernel.configurations": {
    
        "wolframscript": {
            "type": "local",
            "command": "wolframscript",
            "ports": "49152-65535"
        }
    },
    "cmake.configureOnOpen": false
}
```

**Comment by bostick** [comment]
Interesting. I don't understand why the latest changes would allow it to start working, but I'm glad it did!

I was not previously aware that you were also working with the "Wolfram Language Notebook" extension.

We (Wolfram Research) do not manage the "Wolfram Language Notebook" extension. I'm sure the developer will be able to help.
