### ISSUE TITLE
Does it work with the Wolfram Player?

### ISSUE THREAD

**Issue by gdelfino** [WolframResearch/vscode-wolfram#26]
I distribute an application in the EnterpriseCDF format. The application uses a configuration file which is in the WL format (basically a large association full of data settings). These users don't have Mathematica or the Wolfram Engine but they all do have the Wolfram Player.  Can the vs code extension be made to work in this scenario?

**Comment by hifismith** [comment]
Hi Gustavo, I manage my CDF code in VS Code. But everything is saved in a paclet so to deploy it I run “buildCDF” which calls CDFDeploy, and none of the code is actually in a notebook

**Comment by bostick** [comment]
No, the the VS Code extension cannot use the Wolfram Player. Wolfram Player is intended for notebooks. The VS Code extension requires a full kernel running and you can get that with the free Wolfram Engine.
