### ISSUE TITLE
Formatting and Commenting shortcuts

### ISSUE THREAD

**Issue by hifismith** [WolframResearch/vscode-wolfram#3]
I followed the link from the extension page (in VS Code), but that sent me to the Sublime Text repo. Here's what I posted there. Please feel free to delete the irrelevant post:

I love the new plugin. What's stopping me from moving from IntelliJ to VS Code is some of the formatting shortcuts. The two shortcuts that would be really helpful are:

Formatting (add spaces) like cmnd+opt+L in IntelliJ
Wrap selection in (* *) and also unwrap it like cmnd+opt+/ in IntelliJ
Also, navigation to function definitions is easier in IntelliJ. Using shfit+shift and typing my function name is very helpful. In VS Code, cmnd+P only gets me to file names.

Extra points if you can get this to work within other expressions. For Example, I might have a function that caches my user name like this:
With[{user = $Username}, myFunction[string_] := user <> string ]
But in IntelliJ, myFunction isn't found because it's within another expression.

**Comment by bostick** [comment]
It sounds like you are interested in these shortcuts:

Toggle Line Comment (Command + /)

Format Selection ([Command + K Command + F])


If there are issues specific to the VSCode extension for WL, please open another issue.

**Comment by Turgon-Aran-Gondolin** [comment]
It would be great if (Command +/) is toggle comment selected not line comment, just like what's in Mathematica.

**Comment by bostick** [comment]
You can change keyboard shortcuts:
https://code.visualstudio.com/docs/getstarted/keybindings
