### ISSUE TITLE
Could you support unicode characters, just like Mathematica

### ISSUE THREAD

**Issue by ZhuangQu** [WolframResearch/vscode-wolfram#31]
![image](https://user-images.githubusercontent.com/89310792/218366013-e2c3e800-e4f8-461a-9000-089ed2ffbf06.png)
In `Mathematica`, we can use Unicode characters as variable names. But in `vs code`, this doesn't work.

**Comment by userrand** [comment]
![image](https://user-images.githubusercontent.com/114431098/218465028-2efc09fa-3e37-492d-906e-7036a6a1c20c.png)

**Comment by userrand** [comment]
Sorry I also use this and I think I was watching this project for updates or something and got a notification.

 It seems to work for me but there is a somewhat annoying red rectangle around.

![image](https://user-images.githubusercontent.com/114431098/218465707-15f08415-b597-44ad-9cdc-f3bf63c6a0eb.png)

**Comment by ZhuangQu** [comment]
It seems that the Wolfram engine does not support unicode, so we have to escape with `\:`. Could Wolfram engine support it?

**Comment by userrand** [comment]
> It seems that the Wolfram engine does not support unicode, so we have to escape with `\:`. Could Wolfram engine support it?

Unicode works with wolfram engine for Jupyter but it appears with a rectangle around it.

**Comment by bostick** [comment]
Please send a screenshot and/or error messages that you are seeing, and a description of what you are trying and expecting vs. what you are actually seeing. VS Code and Wolfram Language handle Unicode just fine, so I am wondering what the problem is.

**Comment by ZhuangQu** [comment]
![1](https://user-images.githubusercontent.com/89310792/219415560-58444019-25aa-4116-9798-5921c94e078e.png)
It report warnings and Wolfram engine can not accept it.

**Comment by bostick** [comment]
You can disable the warnings by surrounding the code with comments that are interpreted by the system. E.g.:
```
(* :!CodeAnalysis::BeginBlock:: *)
(* :!CodeAnalysis::Disable::UnexpectedLetterlikeCharacter:: *)
(* :!CodeAnalysis::Disable::NonASCIICharacter:: *)

ሴ = 23

(* :!CodeAnalysis::EndBlock:: *)
```

I do not know what you mean by "and wolfram engine can not accept it". If you are seeing more problems besides the warnings, please explain.

**Comment by bostick** [comment]
There is value in catching typos due to non-ASCII characters. For example, recently there was a bug where Cyrillic letter "а" was being used instead of ASCII "a". The NonASCIICharacter warning helped find that.

There could definitely be more work on only warning about "troublesome" non-ASCII characters instead of all non-ASCII characters.

**Comment by ZhuangQu** [comment]
> There is value in catching typos due to non-ASCII characters. For example, recently there was a bug where Cyrillic letter "а" was being used instead of ASCII "a". The NonASCIICharacter warning helped find that.
> 
> There could definitely be more work on only warning about "troublesome" non-ASCII characters instead of all non-ASCII characters.

Don't forget that you are an expansion in VS code! VS code has provides function warning about "troublesome" non-ASCII characters. Please see `editor.unicodeHighlight.ambiguousCharacters` in your settings.

**Comment by bostick** [comment]
That's a good point. You can disable the warnings globally by changing `wolfram.command` in your settings:
```
"wolfram.command": [
        "`kernel`",
        "-noinit",
        "-noprompt",
        "-nopaclet",
        "-nostartuppaclets",
        "-noicon",
        "-run",
        "Needs[\"LSPServer`\"];SetOptions[CodeInspector`CodeInspectCST, \"TagExclusions\" -> {\"UnexpectedLetterlikeCharacter\", \"NonASCIICharacter\"}];LSPServer`StartServer[]"
    ],
```

**Comment by yuriever** [comment]
> That's a good point. You can disable the warnings globally by changing `wolfram.command` in your settings:
> 
> ```
> "wolfram.command": [
>         "`kernel`",
>         "-noinit",
>         "-noprompt",
>         "-nopaclet",
>         "-nostartuppaclets",
>         "-noicon",
>         "-run",
>         "Needs[\"LSPServer`\"];SetOptions[CodeInspector`CodeInspectCST, \"TagExclusions\" -> {\"UnexpectedLetterlikeCharacter\", \"NonASCIICharacter\"}];LSPServer`StartServer[]"
>     ],
> ```

Hi! It seems this isn't working in the new version. I tried the following but failed.
```
    "wolfram.advanced.lsp.command": [
        "lspKernel",
        "-noinit",
        "-noprompt",
        "-nopaclet",
        "-nostartuppaclets",
        "-noicon",
        "-run",
        "Needs[\"LSPServer`\"];SetOptions[CodeInspector`CodeInspectCST,\"TagExclusions\"->{\"UnexpectedLetterlikeCharacter\",\"NonASCIICharacter\"}];LSPServer`StartServer[]",
    ]
```
Could you provide the new settings? Thx!
