### ISSUE TITLE
Unlink from the .m file

### ISSUE THREAD

**Issue by L2Fish** [WolframResearch/vscode-wolfram#37]
.m files are used by both MATLAB and mathematica.
When vscode installs both plugins, the MATLAB file is incorrectly marked as a mathematica file.And MATLAB cannot provide syntax checking.
I wish to unlink the .m file in vscode via settings, and I would try to report the same issue to the official MATLAB plugin.

**Comment by bostick** [comment]
You can change associations in the Preferences UI of VSCode. This has precedence over the default associations of the languages installed.

<img width="1159" alt="Screenshot 2023-07-27 at 9 26 00 AM" src="https://github.com/WolframResearch/vscode-wolfram/assets/183619/6a8f4539-81a5-44cf-a8ec-7acb70e6c8c5">

I'm not sure you can remove associations, but you can give .m files the association of "text" or something similar.

**Comment by L2Fish** [comment]
Thanks for your help!
