### ISSUE TITLE
Documentation on hover doesn't seem to work.

### ISSUE THREAD

**Issue by maximebl** [WolframResearch/vscode-wolfram#4]
The extension description mentions that it provides "Documentation on hover". However when I hover my mouse over any function, all I get back is a tooltip that says `No usage message`.
I'm fairly confident that I have installed the extension correctly, since most of the features including syntax highlighting and diagnostic errors are working correctly.

**Comment by bostick** [comment]
Can you provide some more information?

What is the precise path for `WolframKernel` on your system?

If you start that `WolframKernel` and evaluate `Sin::usage` what is the result?

**Comment by maximebl** [comment]
The path on my system is: `C:\Program Files\Wolfram Research\Wolfram Engine\12.3\WolframKernel.exe` and this is the path being used by the extension.
If I start that kernel and type `Sin::usage` I get nothing back:
```
In[1]:= Sin::usage
Out[1]= Sin::usage
```

**Comment by bostick** [comment]
Right, usage messages are missing in Wolfram Engine in 12.3, but they will be included in the upcoming 13.0 release.

**Comment by maximebl** [comment]
Ok that's good to hear! Thank you.
