### ISSUE TITLE
Minimum supported version should be updated to Mathematica 12.3 due to LSPServer using functions added in 12.3

### ISSUE THREAD

**Issue by dimakolo** [WolframResearch/vscode-wolfram#8]
Due to LSPServer using FromDateString in RunServerDiagnostic the baseline requirements of this plugin should be updated to Mathematica 12.3. While it is possible to force-install version 1.2 of required Paclets that don't include functions introduced in 12.3, this does not sound like a default installation path.

**Comment by bostick** [comment]
No need to change requirements. I will just do a version check and use `DateObject` in earlier versions. Thank you for reporting these issues.
